apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: ghazouanihm/users-api:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
          - name: AUTH_ADDRESS
            value: auth-service

